### ISSUE TITLE
ISO Im;port issue with importing terrain.party map.

### ISSUE THREAD

**Issue by rmjohnson144** [rdiekema/cs-osm-import#1]
This is in response to message on steam workshop.

Here is the log files created by the error.
[error.zip](https://github.com/rdiekema/cs-osm-import/files/672300/error.zip)

**Comment by colakatz** [comment]
I've encountered an error too, I'm guessing the same error.  I copy and past in any coordinates from the readme files from the Terrain.party downloads that I've done (I've tried Vaal Volcano and London, Ontario, Canada and Niagara Falls, inclusive of both US/Canada sides) and it always gives me an error that the game has crashed but if I click on the map editor I can still move around but cannot save or do anything else in the game.  This happens when I click "Import from Terrain.party"

[2017-04-19_134420.zip](https://github.com/rdiekema/cs-osm-import/files/943676/2017-04-19_134420.zip)

**Comment by rdiekema** [comment]
I'm trying to get to the bottom of this, the exception being thrown is really generic and implies that there is either a permissions issue or a memory access violation that runs afoul of some OS level memory protection, i.e. DEP.

**Comment by rmjohnson144** [comment]
Did you try without any workshop?  You seem to have a lot of add-ons that are likely interfering.  Try launching the game with --noWorkshop and --disableMods both at the same time.

Steam launch options for Cities: Skylines w/video.
http://steamcommunity.com/sharedfiles/filedetails/?id=466981085

**Comment by colakatz** [comment]
Well @rmjohnson144 I didn't respond sooner but I hope you realized that if you either of those startup parameters it will remove all mods from the game, including OSM Import, so you can't use it or any other mod.  

@rdiekema  I did do the responsible thing and disabled all mods, except the Pre-hook mod needed for a lot of other mods (not sure if it was needed for this one) and the OSM Importer.  It still crashed on importing the Terrain.party data for the area of 81.123600,43.079781,-81.344981,42.918085

[2017-05-21_120234.zip](https://github.com/rdiekema/cs-osm-import/files/1017136/2017-05-21_120234.zip)

**Comment by XZJSXRomanX** [comment]
I always get an error when I try to import the roads. "value too large or too small". I tried turning all mods off and still, nothing has worked...

**Comment by rdiekema** [comment]
This should be fixed now in the new version of the mod: https://steamcommunity.com/sharedfiles/filedetails/?id=2690250457
